# Generated by Django 2.1 on 2018-08-15 12:54

import auctionsapp.validators
from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Auction',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=250)),
                ('slug', models.SlugField(max_length=250, unique_for_date='publish')),
                ('created', models.DateTimeField(auto_now_add=True, help_text='When auction was created')),
                ('deadline', models.DateField(help_text='Deadline for bids. Minimum of 3 days (dd/mm/yyyy).', validators=[auctionsapp.validators.validate_3_days_from_now])),
                ('description', models.TextField(help_text='Precise description of item(s)', max_length=1000)),
                ('min_price', models.DecimalField(decimal_places=2, help_text='Minimum amount accepted by seller', max_digits=20, validators=[django.core.validators.MinValueValidator(0.0)])),
                ('version', models.IntegerField(default=0, editable=False, help_text='Newest version')),
                ('publish', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('persisted_state', models.IntegerField(choices=[(0, 'Banned'), (1, 'Active'), (2, 'Due'), (3, 'Done')], default=1, editable=False, help_text='Current state of the auction')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='auction_author', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'get_latest_by': 'last_modified',
            },
        ),
        migrations.CreateModel(
            name='Bid',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, help_text='Amount bid', max_digits=20, validators=[django.core.validators.DecimalValidator(decimal_places=2, max_digits=20), django.core.validators.MinValueValidator(0.01)])),
                ('created', models.DateTimeField(auto_now_add=True, help_text='When bid was placed')),
                ('last_modified', models.DateTimeField(auto_now=True, help_text='When bid was last updated')),
                ('auction', models.ForeignKey(help_text='Auction the bid was made on', on_delete=django.db.models.deletion.CASCADE, to='auctionsapp.Auction')),
                ('bidder', models.ForeignKey(help_text='User who placed the bid', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['amount'],
                'get_latest_by': 'last_modified',
            },
        ),
        migrations.AddField(
            model_name='auction',
            name='bidders',
            field=models.ManyToManyField(through='auctionsapp.Bid', to=settings.AUTH_USER_MODEL),
        ),
    ]
