# Generated by Django 2.1 on 2018-08-27 16:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctionsapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='auction',
            name='photo',
            field=models.ImageField(blank=True, upload_to='users/%Y/%m/%d/'),
        ),
    ]
